---
name: Lint
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Create virtual environment in src directory
        run: python -m venv src/venv

      - name: Activate virtual environment and install dependencies
        run: |
          source src/venv/bin/activate
          pip install --upgrade pip
          pip install -r src/requirements.txt -r src/requirements-dev.txt

      - name: Pre-Commit Checks
        uses: pre-commit/action@v3.0.0
