name: Unit Tests
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Create and activate virtual environment in src
        run: |
          python -m venv src/venv
          source src/venv/bin/activate
          pip install --upgrade pip
          pip install -r src/requirements.txt
          pip install pytest pytest-cov  # Ensure pytest and coverage are installed

      - name: Run Unit Tests
        run: |
          source src/venv/bin/activate
          pytest --cov=src --cov-report=xml src/tests/

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
